name: Upload SSL to 1panel
description: Upload SSL to 1panel
branding:
  icon: lock
  color: blue
  
inputs:
  username:
    description: "Login username"
    required: true
  password:
    description: "Login password"
    required: true
  entrance_code:
    description: "Entrance code"
    required: true
  mfa_token:
    description: "MFA token, if available"
    required: false
    default: ""
  login_url:
    description: "Login URL"
    required: true
  mfa_login_url:
    description: "MFA login URL"
    required: false
  upload_url:
    description: "Upload URL"
    required: true
  ssl_id:
    description: "SSL ID for the certificate"
    required: true
  description:
    description: "Description of the upload"
    required: true
  private_key_path:
    description: "path of private key for cert"
    required: true
  certificate_path:
    description: "path of cert"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
        $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        ENTRANCE_CODE: ${{ inputs.entrance_code }}
        MFA_TOKEN: ${{ inputs.mfa_token }}
        LOGIN_URL: ${{ inputs.login_url }}
        MFA_LOGIN_URL: ${{ inputs.mfa_login_url }}
        UPLOAD_URL: ${{ inputs.upload_url }}
        SSL_ID: ${{ inputs.ssl_id }}
        DESCRIPTION: ${{ inputs.description }}
        PRIVATE_KEY_PATH: ${{ inputs.private_key_path }}
        CERTIFICATE_PATH: ${{ inputs.certificate_path }}