name: Upload SSL to 1panel
description: Upload SSL to 1panel
branding:
  icon: lock
  color: blue
  
inputs:
  login_url:
    description: "Login URL"
    required: true
  upload_url:
    description: "Upload URL"
    required: true
  ssl_id:
    description: "SSL ID for the certificate"
    required: true
  description:
    description: "Description of the upload"
    required: true
  private_key_path:
    description: "path of private key for cert"
    required: true
  certificate_path:
    description: "path of cert"
    required: true
  api_key:
    description: "api key for 1panel"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
        $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        LOGIN_URL: ${{ inputs.login_url }}
        UPLOAD_URL: ${{ inputs.upload_url }}
        SSL_ID: ${{ inputs.ssl_id }}
        DESCRIPTION: ${{ inputs.description }}
        PRIVATE_KEY_PATH: ${{ inputs.private_key_path }}
        CERTIFICATE_PATH: ${{ inputs.certificate_path }}
        API_KEY: ${{ inputs.api_key }}